CONTAINER ID   IMAGE                                                      COMMAND                   CREATED        STATUS                             PORTS                                                                                                          NAMES
2b143b843a20   backend_app                                                "docker-entrypoint.s…"    4 weeks ago    Up 5 seconds                                                                                                                                      catmat-app
0e1f38deacd9   padroniza-backend                                          "uvicorn app.main:ap…"    5 weeks ago    Up 4 hours                         0.0.0.0:8001->8000/tcp, [::]:8001->8000/tcp                                                                    padroniza-api
70032e40f73f   public.ecr.aws/supabase/studio:2025.07.28-sha-578b707      "docker-entrypoint.s…"    5 weeks ago    Up 4 hours (healthy)               0.0.0.0:54323->3000/tcp, [::]:54323->3000/tcp                                                                  supabase_studio_supabase
926cd5283f60   public.ecr.aws/supabase/postgres-meta:v0.91.3              "docker-entrypoint.s…"    5 weeks ago    Up 4 hours (healthy)               8080/tcp                                                                                                       supabase_pg_meta_supabase
b31115ce6be4   public.ecr.aws/supabase/storage-api:v1.25.12               "docker-entrypoint.s…"    5 weeks ago    Up 4 hours (healthy)               5000/tcp                                                                                                       supabase_storage_supabase
bb57d479f4fd   public.ecr.aws/supabase/postgrest:v12.2.12                 "/bin/postgrest"          5 weeks ago    Up 4 hours                         3000/tcp                                                                                                       supabase_rest_supabase
a09352eca12a   public.ecr.aws/supabase/realtime:v2.41.9                   "/usr/bin/tini -s -g…"    5 weeks ago    Up 3 hours (healthy)               4000/tcp                                                                                                       supabase_realtime_supabase
32ddd8d8abfd   public.ecr.aws/supabase/mailpit:v1.22.3                    "/mailpit"                5 weeks ago    Up 4 hours (healthy)               1025/tcp, 1110/tcp, 0.0.0.0:54324->8025/tcp, [::]:54324->8025/tcp                                              supabase_inbucket_supabase
0c3f23dab303   public.ecr.aws/supabase/gotrue:v2.177.0                    "auth"                    5 weeks ago    Up 3 hours (healthy)               9999/tcp                                                                                                       supabase_auth_supabase
d118221542f7   public.ecr.aws/supabase/kong:2.8.1                         "sh -c 'cat <<'EOF' …"    5 weeks ago    Up 4 hours (healthy)               8001/tcp, 8088/tcp, 8443-8444/tcp, 0.0.0.0:54321->8000/tcp, [::]:54321->8000/tcp                               supabase_kong_supabase
88fa3e6d6b29   public.ecr.aws/supabase/vector:0.28.1-alpine               "sh -c 'cat <<'EOF' …"    5 weeks ago    Up 4 hours (healthy)                                                                                                                              supabase_vector_supabase
622d38f0d866   public.ecr.aws/supabase/logflare:1.14.2                    "sh -c 'cat <<'EOF' …"    5 weeks ago    Up 3 hours (healthy)               0.0.0.0:54327->4000/tcp, [::]:54327->4000/tcp                                                                  supabase_analytics_supabase
26401c106e80   public.ecr.aws/supabase/postgres:15.8.1.085                "sh -c '\ncat <<'EOF'…"   5 weeks ago    Up 4 hours (healthy)               0.0.0.0:54322->5432/tcp, [::]:54322->5432/tcp                                                                  supabase_db_supabase
806f4e4ee8b1   supabase/storage-api:v1.23.0                               "docker-entrypoint.s…"    5 weeks ago    Up 16 seconds (health: starting)   5000/tcp                                                                                                       supabase-storage
aa77f6e910a4   supabase/edge-runtime:v1.67.4                              "edge-runtime start …"    5 weeks ago    Up 4 hours                                                                                                                                        supabase-edge-functions
8b930b2e230c   kong:2.8.1                                                 "bash -c 'eval \"echo…"   5 weeks ago    Up 4 hours (healthy)               0.0.0.0:8000->8000/tcp, [::]:8000->8000/tcp, 8001/tcp, 0.0.0.0:8443->8443/tcp, [::]:8443->8443/tcp, 8444/tcp   supabase-kong
38b91958e71d   supabase/studio:2025.06.02-sha-8f2993d                     "docker-entrypoint.s…"    5 weeks ago    Up 4 hours (healthy)               0.0.0.0:3000->3000/tcp, [::]:3000->3000/tcp                                                                    supabase-studio
19d9a8e4cc75   supabase/postgres-meta:v0.89.3                             "docker-entrypoint.s…"    5 weeks ago    Up 4 hours (healthy)               8080/tcp                                                                                                       supabase-meta
dae27d23aa24   postgrest/postgrest:v12.2.12                               "postgrest"               5 weeks ago    Up 4 hours                         3000/tcp                                                                                                       supabase-rest
9ab2c5d5576d   supabase/logflare:1.14.2                                   "sh run.sh"               5 weeks ago    Up 15 seconds (health: starting)   0.0.0.0:4000->4000/tcp, [::]:4000->4000/tcp                                                                    supabase-analytics
6732c899c969   darthsim/imgproxy:v3.8.0                                   "imgproxy"                5 weeks ago    Up 4 hours (healthy)               8080/tcp                                                                                                       supabase-imgproxy
3795289e10e0   timberio/vector:0.28.1-alpine                              "/usr/local/bin/vect…"    5 weeks ago    Up 4 hours (healthy)                                                                                                                              supabase-vector
7c88e077c3f4   apache/hop:2.8.0                                           "/bin/bash /opt/hop/…"    6 weeks ago    Up 4 hours                         8079/tcp, 0.0.0.0:8080->8080/tcp, [::]:8080->8080/tcp                                                          hop-web-server
96f365d64fb7   postgres:15                                                "docker-entrypoint.s…"    6 weeks ago    Up 4 hours                         0.0.0.0:5433->5432/tcp, [::]:5433->5432/tcp                                                                    impressive_martijn-postgres-1
